<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.400" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.7.400.109" />
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\POC_ITAU.Application\POC_ITAU.Application\POC_ITAU.Application.csproj" />
    <ProjectReference Include="..\POC_ITAU.Persistence\POC_ITAU.Persistence\POC_ITAU.Persistence.csproj" />
  </ItemGroup>

</Project>
